name: Run API Tests

on:
  push:
    branches: [develop master]
  pull_request:
    branches: [develop master]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set up docker
      uses: docker/setup-buildx-action@v2

    - name: cache for docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build docker image
      run: docker build -t hexis-challenge-api-test .

    - name: Run tests in docker
      run: docker run --rm -v ${{ github.workspace }}/reports:/app/reports hexis-challenge-api-test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.txt